### ISSUE TITLE
Add Pinephone LoRa device to Meshtastic

### ISSUE THREAD

**Issue by joshbowyer** [meshtastic/Meshtastic#296] opened 2022-03-24 18:13 UTC
Resubmitting as more specific issue:

I would really love to be able to use the Meshtastic network with this: https://pine64.com/product/pinephone-pinephone-pro-pindio-lora-add-on-case/

Basically, it is a LoRa chip integrated into the Pinephone, which is a full Linux smartphone. Is there a way to enable this chip to talk on the Meshtastic network? Would this require a driver/firmware? As the Pine64 LoRa project picks up speed this may be a good device to enable support for.

Info on this chip and driver progress:

https://github.com/lupyuen/pinephone-lora
https://codingfield.com/blog/2021-11/a-driver-for-the-pinephone-lora-backplate/

**Comment by jfirwin** [comment] 2022-03-24 19:24
Hi @joshbowyer. Thank you for your interest in Meshtastic. The PinePhone LoRa backplate is something on our wishlist of supported devices. It would be amazing! At this point in time our main objective is to get a stable version of Meshtastic running on Linux.

A few of the devs have the PineDio LoRa USB dongle, and I'm not sure that anyone has the backplate yet. Once some level of stability on Linux is achieved, the LoRa case would be something we could extend functionality.

We are all volunteers. I don't know of any devs that own this device at present. There is work being done on the Pinedio, and that work should be able to be extendable to the device you requested. It's definitely on our radar.

We like to keep our issues fairly actionable, and as such I will close this as a duplicate of #292

**Closed by jfirwin** 2022-03-24 19:24 UTC
